/**
 * Desktop build orchestrator (run via `npm run desktop:build`, after
 * `react-router build` and before `tauri build`):
 *   1. generate the embedded-asset manifest for build/client
 *   2. generate schema.generated.sql from the drizzle schema
 *   3. bun build --compile → dist/sprout-account (arm64 binary)
 *   4. copy the binary as the Tauri sidecar (src-tauri/binaries/…)
 * Tauri then wraps it in a frameless native window and bundles the .app/.dmg.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { $ } from "bun";

const ROOT = path.resolve(import.meta.dir, "../..");
const CLIENT_DIR = path.join(ROOT, "build", "client");
const DESKTOP_DIR = import.meta.dir;
const DIST = path.join(ROOT, "dist");

if (!fs.existsSync(path.join(CLIENT_DIR, "assets"))) {
  console.error("build/client not found — run `react-router build` first.");
  process.exit(1);
}
fs.mkdirSync(DIST, { recursive: true });

// ——— 1. asset manifest ———
function walk(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? walk(full) : [full];
  });
}
const files = walk(CLIENT_DIR).filter((f) => !f.endsWith(".DS_Store"));
const lines: string[] = ["// AUTO-GENERATED by scripts/desktop/build.ts — do not edit."];
const entries: string[] = [];
files.forEach((file, i) => {
  const urlPath = "/" + path.relative(CLIENT_DIR, file).split(path.sep).join("/");
  const rel = "./" + path.relative(DESKTOP_DIR, file).split(path.sep).join("/");
  lines.push(`import a${i} from ${JSON.stringify(rel)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: a${i},`);
});
lines.push("", "export const assetMap: Record<string, string> = {", ...entries, "};");
fs.writeFileSync(path.join(DESKTOP_DIR, "assets.generated.ts"), lines.join("\n"));
console.log(`✓ asset manifest: ${files.length} files`);

// ——— 2. schema dump (fresh temp db via drizzle-kit, then .schema) ———
const tmpDb = path.join(os.tmpdir(), `sprout-schema-${Date.now()}.db`);
await $`npx drizzle-kit push --force`
  .cwd(ROOT)
  .env({ ...process.env, DATABASE_PATH: tmpDb, SPROUT_LOCAL_SCHEMA_DUMP: "1" })
  .quiet();
const schemaSql = await $`sqlite3 ${tmpDb} .schema`.text();
const cleanedSchema = schemaSql
  .split("\n")
  // sqlite-internal objects appear in dumps but cannot be created manually
  .filter((l) => !l.includes("sqlite_sequence") && !l.includes("__drizzle_migrations"))
  .join("\n");
fs.writeFileSync(path.join(DESKTOP_DIR, "schema.generated.sql"), cleanedSchema);
fs.rmSync(tmpDb, { force: true });
console.log("✓ schema.generated.sql");

// ——— 3. compile ———
const binary = path.join(DIST, "sprout-account");
await $`bun build --compile --minify --target=bun-darwin-arm64 ${path.join(
  DESKTOP_DIR,
  "server.ts",
)} --outfile ${binary}`.cwd(ROOT);
console.log(`✓ compiled ${binary}`);

// ——— 4. sidecar for Tauri (must carry the target-triple suffix) ———
const sidecarDir = path.join(ROOT, "src-tauri", "binaries");
fs.mkdirSync(sidecarDir, { recursive: true });
const sidecar = path.join(sidecarDir, "sprout-server-aarch64-apple-darwin");
fs.copyFileSync(binary, sidecar);
fs.chmodSync(sidecar, 0o755);
console.log("✓ sidecar → src-tauri/binaries/");

const size = fs.statSync(binary).size;
console.log(`\nServer binary ready (${(size / 1e6).toFixed(1)} MB). Now run: npx tauri build`);
